# 相当于脚本用途的一个声明
name: GitHub Action测试
# 触发脚本的事件  这里为发布release之后触发
on:
  # 支持手动触发构建
  workflow_dispatch:
# 定义一个发行任务
jobs:
  test:
    # 任务运行的环境
    runs-on: ubuntu-20.04
    strategy:
      # When set to true, GitHub cancels all in-progress jobs if any matrix job fails. Default: true
      fail-fast: false
    # 任务的步骤
    steps:
      # step1 
      - name: GitHub - 执行的系统类型
        run: uname -an
      - run: echo "打印环境变量 触发工作流程的 web 挂钩事件的名称 $GITHUB_EVENT_NAME"
      - run: echo "打印环境变量 具有完整 web 挂钩事件有效负载的文件路径 $GITHUB_EVENT_PATH"
      - run: echo "打印环境变量 GitHub 工作空间目录路径 $GITHUB_WORKSPACE"
      - run: echo "打印环境变量 触发工作流程的提交 SHA $GITHUB_SHA"
      - run: echo "打印环境变量 触发工作流程的分支或标记参考 $GITHUB_REF"
      - run: echo "打印环境变量 仅为拉取请求事件设置。 头部分支的名称 $GITHUB_HEAD_REF"
      - run: echo "打印环境变量 仅为拉取请求事件设置。 基础分支的名称 $GITHUB_BASE_REF"
      - run: echo "打印环境变量 返回 GitHub 服务器的 URL $GITHUB_SERVER_URL"
      - run: echo "打印环境变量 返回 API URL $GITHUB_API_URL"
      - run: echo "打印环境变量 返回 GraphQL API URL $GITHUB_GRAPHQL_URL"
